# Generated by Django 5.2.4 on 2025-07-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedcsv',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='uploadedcsv',
            name='file',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
