# Generated by Django 5.2.4 on 2025-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uploaded_at_uploadedcsv_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcsv',
            name='file',
            field=models.FileField(upload_to='csvs/'),
        ),
    ]
